# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.body149 import Body149  # noqa: E501
from swagger_client.rest import ApiException


class TestBody149(unittest.TestCase):
    """Body149 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBody149(self):
        """Test Body149"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.body149.Body149()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
