# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.body128 import Body128  # noqa: E501
from swagger_client.rest import ApiException


class TestBody128(unittest.TestCase):
    """Body128 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBody128(self):
        """Test Body128"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.body128.Body128()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
