# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.body120 import Body120  # noqa: E501
from swagger_client.rest import ApiException


class TestBody120(unittest.TestCase):
    """Body120 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBody120(self):
        """Test Body120"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.body120.Body120()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
