# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.body134 import Body134  # noqa: E501
from swagger_client.rest import ApiException


class TestBody134(unittest.TestCase):
    """Body134 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBody134(self):
        """Test Body134"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.body134.Body134()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
