# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_account(self):
        """Test case for create_account

        """
        pass

    def test_create_address(self):
        """Test case for create_address

        """
        pass

    def test_create_bill(self):
        """Test case for create_bill

        """
        pass

    def test_create_contact(self):
        """Test case for create_contact

        """
        pass

    def test_create_database(self):
        """Test case for create_database

        """
        pass

    def test_create_database_user(self):
        """Test case for create_database_user

        """
        pass

    def test_create_domain(self):
        """Test case for create_domain

        """
        pass

    def test_create_list(self):
        """Test case for create_list

        """
        pass

    def test_create_mailbox(self):
        """Test case for create_mailbox

        """
        pass

    def test_create_obtain_auth_token(self):
        """Test case for create_obtain_auth_token

        """
        pass

    def test_create_order(self):
        """Test case for create_order

        """
        pass

    def test_create_payment_source(self):
        """Test case for create_payment_source

        """
        pass

    def test_create_queue(self):
        """Test case for create_queue

        """
        pass

    def test_create_saa_s(self):
        """Test case for create_saa_s

        """
        pass

    def test_create_system_user(self):
        """Test case for create_system_user

        """
        pass

    def test_create_ticket(self):
        """Test case for create_ticket

        """
        pass

    def test_create_transaction(self):
        """Test case for create_transaction

        """
        pass

    def test_create_web_app(self):
        """Test case for create_web_app

        """
        pass

    def test_create_website(self):
        """Test case for create_website

        """
        pass

    def test_destroy_account(self):
        """Test case for destroy_account

        """
        pass

    def test_destroy_address(self):
        """Test case for destroy_address

        """
        pass

    def test_destroy_bill(self):
        """Test case for destroy_bill

        """
        pass

    def test_destroy_contact(self):
        """Test case for destroy_contact

        """
        pass

    def test_destroy_database(self):
        """Test case for destroy_database

        """
        pass

    def test_destroy_database_user(self):
        """Test case for destroy_database_user

        """
        pass

    def test_destroy_domain(self):
        """Test case for destroy_domain

        """
        pass

    def test_destroy_list(self):
        """Test case for destroy_list

        """
        pass

    def test_destroy_mailbox(self):
        """Test case for destroy_mailbox

        """
        pass

    def test_destroy_order(self):
        """Test case for destroy_order

        """
        pass

    def test_destroy_payment_source(self):
        """Test case for destroy_payment_source

        """
        pass

    def test_destroy_queue(self):
        """Test case for destroy_queue

        """
        pass

    def test_destroy_saa_s(self):
        """Test case for destroy_saa_s

        """
        pass

    def test_destroy_system_user(self):
        """Test case for destroy_system_user

        """
        pass

    def test_destroy_ticket(self):
        """Test case for destroy_ticket

        """
        pass

    def test_destroy_transaction(self):
        """Test case for destroy_transaction

        """
        pass

    def test_destroy_web_app(self):
        """Test case for destroy_web_app

        """
        pass

    def test_destroy_website(self):
        """Test case for destroy_website

        """
        pass

    def test_document_bill(self):
        """Test case for document_bill

        """
        pass

    def test_list_accounts(self):
        """Test case for list_accounts

        """
        pass

    def test_list_address(self):
        """Test case for list_address

        """
        pass

    def test_list_api_roots(self):
        """Test case for list_api_roots

        """
        pass

    def test_list_bills(self):
        """Test case for list_bills

        """
        pass

    def test_list_contacts(self):
        """Test case for list_contacts

        """
        pass

    def test_list_database_users(self):
        """Test case for list_database_users

        """
        pass

    def test_list_databases(self):
        """Test case for list_databases

        """
        pass

    def test_list_domains(self):
        """Test case for list_domains

        """
        pass

    def test_list_lists(self):
        """Test case for list_lists

        """
        pass

    def test_list_mailboxs(self):
        """Test case for list_mailboxs

        """
        pass

    def test_list_orders(self):
        """Test case for list_orders

        """
        pass

    def test_list_payment_sources(self):
        """Test case for list_payment_sources

        """
        pass

    def test_list_queues(self):
        """Test case for list_queues

        """
        pass

    def test_list_saa_ss(self):
        """Test case for list_saa_ss

        """
        pass

    def test_list_system_users(self):
        """Test case for list_system_users

        """
        pass

    def test_list_tickets(self):
        """Test case for list_tickets

        """
        pass

    def test_list_transactions(self):
        """Test case for list_transactions

        """
        pass

    def test_list_web_apps(self):
        """Test case for list_web_apps

        """
        pass

    def test_list_websites(self):
        """Test case for list_websites

        """
        pass

    def test_mark_as_read_ticket(self):
        """Test case for mark_as_read_ticket

        """
        pass

    def test_mark_as_unread_ticket(self):
        """Test case for mark_as_unread_ticket

        """
        pass

    def test_partial_update_account(self):
        """Test case for partial_update_account

        """
        pass

    def test_partial_update_address(self):
        """Test case for partial_update_address

        """
        pass

    def test_partial_update_bill(self):
        """Test case for partial_update_bill

        """
        pass

    def test_partial_update_contact(self):
        """Test case for partial_update_contact

        """
        pass

    def test_partial_update_database(self):
        """Test case for partial_update_database

        """
        pass

    def test_partial_update_database_user(self):
        """Test case for partial_update_database_user

        """
        pass

    def test_partial_update_domain(self):
        """Test case for partial_update_domain

        """
        pass

    def test_partial_update_list(self):
        """Test case for partial_update_list

        """
        pass

    def test_partial_update_mailbox(self):
        """Test case for partial_update_mailbox

        """
        pass

    def test_partial_update_order(self):
        """Test case for partial_update_order

        """
        pass

    def test_partial_update_payment_source(self):
        """Test case for partial_update_payment_source

        """
        pass

    def test_partial_update_queue(self):
        """Test case for partial_update_queue

        """
        pass

    def test_partial_update_saa_s(self):
        """Test case for partial_update_saa_s

        """
        pass

    def test_partial_update_system_user(self):
        """Test case for partial_update_system_user

        """
        pass

    def test_partial_update_ticket(self):
        """Test case for partial_update_ticket

        """
        pass

    def test_partial_update_transaction(self):
        """Test case for partial_update_transaction

        """
        pass

    def test_partial_update_web_app(self):
        """Test case for partial_update_web_app

        """
        pass

    def test_partial_update_website(self):
        """Test case for partial_update_website

        """
        pass

    def test_retrieve_account(self):
        """Test case for retrieve_account

        """
        pass

    def test_retrieve_address(self):
        """Test case for retrieve_address

        """
        pass

    def test_retrieve_bill(self):
        """Test case for retrieve_bill

        """
        pass

    def test_retrieve_contact(self):
        """Test case for retrieve_contact

        """
        pass

    def test_retrieve_database(self):
        """Test case for retrieve_database

        """
        pass

    def test_retrieve_database_user(self):
        """Test case for retrieve_database_user

        """
        pass

    def test_retrieve_domain(self):
        """Test case for retrieve_domain

        """
        pass

    def test_retrieve_list(self):
        """Test case for retrieve_list

        """
        pass

    def test_retrieve_mailbox(self):
        """Test case for retrieve_mailbox

        """
        pass

    def test_retrieve_order(self):
        """Test case for retrieve_order

        """
        pass

    def test_retrieve_payment_source(self):
        """Test case for retrieve_payment_source

        """
        pass

    def test_retrieve_queue(self):
        """Test case for retrieve_queue

        """
        pass

    def test_retrieve_saa_s(self):
        """Test case for retrieve_saa_s

        """
        pass

    def test_retrieve_system_user(self):
        """Test case for retrieve_system_user

        """
        pass

    def test_retrieve_ticket(self):
        """Test case for retrieve_ticket

        """
        pass

    def test_retrieve_transaction(self):
        """Test case for retrieve_transaction

        """
        pass

    def test_retrieve_web_app(self):
        """Test case for retrieve_web_app

        """
        pass

    def test_retrieve_website(self):
        """Test case for retrieve_website

        """
        pass

    def test_set_password_account(self):
        """Test case for set_password_account

        """
        pass

    def test_set_password_database_user(self):
        """Test case for set_password_database_user

        """
        pass

    def test_set_password_list(self):
        """Test case for set_password_list

        """
        pass

    def test_set_password_mailbox(self):
        """Test case for set_password_mailbox

        """
        pass

    def test_set_password_system_user(self):
        """Test case for set_password_system_user

        """
        pass

    def test_update_account(self):
        """Test case for update_account

        """
        pass

    def test_update_address(self):
        """Test case for update_address

        """
        pass

    def test_update_bill(self):
        """Test case for update_bill

        """
        pass

    def test_update_contact(self):
        """Test case for update_contact

        """
        pass

    def test_update_database(self):
        """Test case for update_database

        """
        pass

    def test_update_database_user(self):
        """Test case for update_database_user

        """
        pass

    def test_update_domain(self):
        """Test case for update_domain

        """
        pass

    def test_update_list(self):
        """Test case for update_list

        """
        pass

    def test_update_mailbox(self):
        """Test case for update_mailbox

        """
        pass

    def test_update_order(self):
        """Test case for update_order

        """
        pass

    def test_update_payment_source(self):
        """Test case for update_payment_source

        """
        pass

    def test_update_queue(self):
        """Test case for update_queue

        """
        pass

    def test_update_saa_s(self):
        """Test case for update_saa_s

        """
        pass

    def test_update_system_user(self):
        """Test case for update_system_user

        """
        pass

    def test_update_ticket(self):
        """Test case for update_ticket

        """
        pass

    def test_update_transaction(self):
        """Test case for update_transaction

        """
        pass

    def test_update_web_app(self):
        """Test case for update_web_app

        """
        pass

    def test_update_website(self):
        """Test case for update_website

        """
        pass

    def test_view_zone_domain(self):
        """Test case for view_zone_domain

        """
        pass


if __name__ == '__main__':
    unittest.main()
