# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.body34 import Body34  # noqa: E501
from swagger_client.rest import ApiException


class TestBody34(unittest.TestCase):
    """Body34 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBody34(self):
        """Test Body34"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.body34.Body34()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
