# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ApiaccountsBillcontact(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'address': 'str',
        'city': 'str',
        'zipcode': 'str',
        'country': 'str',
        'vat': 'str'
    }

    attribute_map = {
        'name': 'name',
        'address': 'address',
        'city': 'city',
        'zipcode': 'zipcode',
        'country': 'country',
        'vat': 'vat'
    }

    def __init__(self, name=None, address=None, city=None, zipcode=None, country=None, vat=None):  # noqa: E501
        """ApiaccountsBillcontact - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._address = None
        self._city = None
        self._zipcode = None
        self._country = None
        self._vat = None
        self.discriminator = None
        if name is not None:
            self.name = name
        self.address = address
        if city is not None:
            self.city = city
        self.zipcode = zipcode
        if country is not None:
            self.country = country
        self.vat = vat

    @property
    def name(self):
        """Gets the name of this ApiaccountsBillcontact.  # noqa: E501

        Account full name will be used when left blank.  # noqa: E501

        :return: The name of this ApiaccountsBillcontact.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ApiaccountsBillcontact.

        Account full name will be used when left blank.  # noqa: E501

        :param name: The name of this ApiaccountsBillcontact.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def address(self):
        """Gets the address of this ApiaccountsBillcontact.  # noqa: E501


        :return: The address of this ApiaccountsBillcontact.  # noqa: E501
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address):
        """Sets the address of this ApiaccountsBillcontact.


        :param address: The address of this ApiaccountsBillcontact.  # noqa: E501
        :type: str
        """
        if address is None:
            raise ValueError("Invalid value for `address`, must not be `None`")  # noqa: E501

        self._address = address

    @property
    def city(self):
        """Gets the city of this ApiaccountsBillcontact.  # noqa: E501


        :return: The city of this ApiaccountsBillcontact.  # noqa: E501
        :rtype: str
        """
        return self._city

    @city.setter
    def city(self, city):
        """Sets the city of this ApiaccountsBillcontact.


        :param city: The city of this ApiaccountsBillcontact.  # noqa: E501
        :type: str
        """

        self._city = city

    @property
    def zipcode(self):
        """Gets the zipcode of this ApiaccountsBillcontact.  # noqa: E501


        :return: The zipcode of this ApiaccountsBillcontact.  # noqa: E501
        :rtype: str
        """
        return self._zipcode

    @zipcode.setter
    def zipcode(self, zipcode):
        """Sets the zipcode of this ApiaccountsBillcontact.


        :param zipcode: The zipcode of this ApiaccountsBillcontact.  # noqa: E501
        :type: str
        """
        if zipcode is None:
            raise ValueError("Invalid value for `zipcode`, must not be `None`")  # noqa: E501

        self._zipcode = zipcode

    @property
    def country(self):
        """Gets the country of this ApiaccountsBillcontact.  # noqa: E501


        :return: The country of this ApiaccountsBillcontact.  # noqa: E501
        :rtype: str
        """
        return self._country

    @country.setter
    def country(self, country):
        """Sets the country of this ApiaccountsBillcontact.


        :param country: The country of this ApiaccountsBillcontact.  # noqa: E501
        :type: str
        """

        self._country = country

    @property
    def vat(self):
        """Gets the vat of this ApiaccountsBillcontact.  # noqa: E501


        :return: The vat of this ApiaccountsBillcontact.  # noqa: E501
        :rtype: str
        """
        return self._vat

    @vat.setter
    def vat(self, vat):
        """Sets the vat of this ApiaccountsBillcontact.


        :param vat: The vat of this ApiaccountsBillcontact.  # noqa: E501
        :type: str
        """
        if vat is None:
            raise ValueError("Invalid value for `vat`, must not be `None`")  # noqa: E501

        self._vat = vat

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApiaccountsBillcontact, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiaccountsBillcontact):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
