# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Body52(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'state': 'str',
        'amount': 'float',
        'currency': 'str',
        'bill': 'str',
        'source': 'str'
    }

    attribute_map = {
        'state': 'state',
        'amount': 'amount',
        'currency': 'currency',
        'bill': 'bill',
        'source': 'source'
    }

    def __init__(self, state=None, amount=None, currency=None, bill=None, source=None):  # noqa: E501
        """Body52 - a model defined in Swagger"""  # noqa: E501
        self._state = None
        self._amount = None
        self._currency = None
        self._bill = None
        self._source = None
        self.discriminator = None
        if state is not None:
            self.state = state
        if amount is not None:
            self.amount = amount
        if currency is not None:
            self.currency = currency
        if bill is not None:
            self.bill = bill
        if source is not None:
            self.source = source

    @property
    def state(self):
        """Gets the state of this Body52.  # noqa: E501


        :return: The state of this Body52.  # noqa: E501
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this Body52.


        :param state: The state of this Body52.  # noqa: E501
        :type: str
        """

        self._state = state

    @property
    def amount(self):
        """Gets the amount of this Body52.  # noqa: E501


        :return: The amount of this Body52.  # noqa: E501
        :rtype: float
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this Body52.


        :param amount: The amount of this Body52.  # noqa: E501
        :type: float
        """

        self._amount = amount

    @property
    def currency(self):
        """Gets the currency of this Body52.  # noqa: E501


        :return: The currency of this Body52.  # noqa: E501
        :rtype: str
        """
        return self._currency

    @currency.setter
    def currency(self, currency):
        """Sets the currency of this Body52.


        :param currency: The currency of this Body52.  # noqa: E501
        :type: str
        """

        self._currency = currency

    @property
    def bill(self):
        """Gets the bill of this Body52.  # noqa: E501


        :return: The bill of this Body52.  # noqa: E501
        :rtype: str
        """
        return self._bill

    @bill.setter
    def bill(self, bill):
        """Sets the bill of this Body52.


        :param bill: The bill of this Body52.  # noqa: E501
        :type: str
        """

        self._bill = bill

    @property
    def source(self):
        """Gets the source of this Body52.  # noqa: E501


        :return: The source of this Body52.  # noqa: E501
        :rtype: str
        """
        return self._source

    @source.setter
    def source(self, source):
        """Sets the source of this Body52.


        :param source: The source of this Body52.  # noqa: E501
        :type: str
        """

        self._source = source

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Body52, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Body52):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
