# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Body115(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'type': 'str',
        'options': 'ApiwebappsOptions',
        'data': 'str'
    }

    attribute_map = {
        'name': 'name',
        'type': 'type',
        'options': 'options',
        'data': 'data'
    }

    def __init__(self, name=None, type=None, options=None, data=None):  # noqa: E501
        """Body115 - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._type = None
        self._options = None
        self._data = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if type is not None:
            self.type = type
        if options is not None:
            self.options = options
        if data is not None:
            self.data = data

    @property
    def name(self):
        """Gets the name of this Body115.  # noqa: E501

        The app will be installed in %(home)s/webapps/%(app_name)s  # noqa: E501

        :return: The name of this Body115.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Body115.

        The app will be installed in %(home)s/webapps/%(app_name)s  # noqa: E501

        :param name: The name of this Body115.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def type(self):
        """Gets the type of this Body115.  # noqa: E501


        :return: The type of this Body115.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Body115.


        :param type: The type of this Body115.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def options(self):
        """Gets the options of this Body115.  # noqa: E501


        :return: The options of this Body115.  # noqa: E501
        :rtype: ApiwebappsOptions
        """
        return self._options

    @options.setter
    def options(self, options):
        """Sets the options of this Body115.


        :param options: The options of this Body115.  # noqa: E501
        :type: ApiwebappsOptions
        """

        self._options = options

    @property
    def data(self):
        """Gets the data of this Body115.  # noqa: E501


        :return: The data of this Body115.  # noqa: E501
        :rtype: str
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this Body115.


        :param data: The data of this Body115.  # noqa: E501
        :type: str
        """

        self._data = data

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Body115, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Body115):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
