# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Body56(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'queue': 'str',
        'subject': 'str',
        'description': 'str',
        'state': 'str'
    }

    attribute_map = {
        'queue': 'queue',
        'subject': 'subject',
        'description': 'description',
        'state': 'state'
    }

    def __init__(self, queue=None, subject=None, description=None, state=None):  # noqa: E501
        """Body56 - a model defined in Swagger"""  # noqa: E501
        self._queue = None
        self._subject = None
        self._description = None
        self._state = None
        self.discriminator = None
        if queue is not None:
            self.queue = queue
        self.subject = subject
        self.description = description
        if state is not None:
            self.state = state

    @property
    def queue(self):
        """Gets the queue of this Body56.  # noqa: E501


        :return: The queue of this Body56.  # noqa: E501
        :rtype: str
        """
        return self._queue

    @queue.setter
    def queue(self, queue):
        """Sets the queue of this Body56.


        :param queue: The queue of this Body56.  # noqa: E501
        :type: str
        """

        self._queue = queue

    @property
    def subject(self):
        """Gets the subject of this Body56.  # noqa: E501


        :return: The subject of this Body56.  # noqa: E501
        :rtype: str
        """
        return self._subject

    @subject.setter
    def subject(self, subject):
        """Sets the subject of this Body56.


        :param subject: The subject of this Body56.  # noqa: E501
        :type: str
        """
        if subject is None:
            raise ValueError("Invalid value for `subject`, must not be `None`")  # noqa: E501

        self._subject = subject

    @property
    def description(self):
        """Gets the description of this Body56.  # noqa: E501


        :return: The description of this Body56.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this Body56.


        :param description: The description of this Body56.  # noqa: E501
        :type: str
        """
        if description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501

        self._description = description

    @property
    def state(self):
        """Gets the state of this Body56.  # noqa: E501


        :return: The state of this Body56.  # noqa: E501
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this Body56.


        :param state: The state of this Body56.  # noqa: E501
        :type: str
        """

        self._state = state

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Body56, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Body56):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
